#!/usr/bin/with-contenv bash

if [ ! -d "/app/clarkson/dist" ]; then

    URL=${URL:-http://localhost:3000}
    ENABLE_REGISTRATIONS=${ENABLE_REGISTRATIONS:-false}

    echo "--------------------------------------------------------------------------------------------"
    echo "Clarkson hasn't been built yet (this must be the fist run of the container). Building now..."
    echo "--------------------------------------------------------------------------------------------"

    echo "URL: ${URL}"
    echo "Registrations enabled: ${ENABLE_REGISTRATIONS}"

    cd /app/clarkson
    ts-node ./scripts/set-env.ts --environment=prod --url=$URL --enableRegistrations=$ENABLE_REGISTRATIONS
    ng build --prod

fi
