#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*             This image is deprecated.              *
*      We will not offer support for this image      *
*             and it will not be updated.            *
*                                                    *
*                                                    *
******************************************************
******************************************************

We recommend looking at Hammond as a replacement:
https://github.com/akhilrex/hammond


******************************************************
******************************************************'
